# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "290fd1a342ce091d04855064ca310d33"
name = "hello-world-product-app"
handle = "hello-world-product-app-5"
application_url = "https://work-totals-photographer-ciao.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://work-totals-photographer-ciao.trycloudflare.com/auth/callback",
  "https://work-totals-photographer-ciao.trycloudflare.com/auth/shopify/callback",
  "https://work-totals-photographer-ciao.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
